"""Fig 1 — matrix batch time-series.

Reads from canonical artefacts at HEAD:
  results_<scenario>_matrix.txt (gitignored, regenerated by the
                                  rerun_all_postfix.sh cascade)
Parses the Slavic-share checkpoint table at the end of each file
(7 checkpoints per scenario: years 0, 25, 50, 100, 150, 200, 260).

Generates docs/paper/figures/fig1_matrix_timeseries.{pdf,png}.

Per response5: no simulation calls; figures read from artefacts.
"""
from __future__ import annotations

import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[3]
OUT_DIR = Path(__file__).resolve().parent

SCENARIOS = [
    ("slavic1", "Slavic 1 (~1 M migrants)", "blue"),
    ("slavic2", "Slavic 2 (~3 M migrants)", "green"),
    ("slavic3", "Slavic 3 (~5 M migrants)", "red"),
    ("arabic",  "Arabic (~1 M migrants)",   "purple"),
]
SCENARIO_START_YEAR = {"slavic1": 600, "slavic2": 600, "slavic3": 600, "arabic": 630}

CHECKPOINT_LINE = re.compile(
    r"year\s+(\d+):\s+([\d.]+)%\s*\+/-\s*([\d.]+)%"
)


def parse_checkpoints(path: Path) -> tuple[list[int], list[float], list[float]]:
    text = path.read_text()
    # The Slavic-share checkpoint block is at the end of the file.
    block = text.split("Slavic-share checkpoints")[-1]
    years, means, sds = [], [], []
    for m in CHECKPOINT_LINE.finditer(block):
        years.append(int(m.group(1)))
        means.append(float(m.group(2)))
        sds.append(float(m.group(3)))
    return years, means, sds


def main() -> None:
    fig, ax = plt.subplots(figsize=(8.5, 5.5))

    for scen, label, color in SCENARIOS:
        path = REPO_ROOT / f"results_{scen}_matrix.txt"
        if not path.exists():
            raise FileNotFoundError(f"Missing canonical artefact: {path}")
        offsets, means, sds = parse_checkpoints(path)
        years = np.array([SCENARIO_START_YEAR[scen] + o for o in offsets])
        means_arr = np.array(means)
        sds_arr = np.array(sds)
        ax.plot(years, means_arr, "o-", label=label, color=color, linewidth=2, markersize=5)
        ax.fill_between(
            years, means_arr - sds_arr, means_arr + sds_arr, color=color, alpha=0.18
        )

    ax.set_xlabel("Year (CE)")
    ax.set_ylabel("Slavic linguistic share (%)")
    ax.set_title(
        "Fig 1 — Slavic linguistic share over time, four scenarios "
        "(matrix batch, 10 runs, seed 42)"
    )
    ax.set_ylim(0, 100)
    ax.set_xlim(600, 870)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper left", framealpha=0.95)
    # Reference lines
    ax.axhline(80, color="grey", linestyle=":", linewidth=1, alpha=0.6)
    ax.text(605, 81.5, "historical Slavic ~80 %+", fontsize=8, color="grey")
    ax.axhline(55, color="grey", linestyle=":", linewidth=1, alpha=0.6)
    ax.text(635, 56.5, "historical Arabic ~55 %", fontsize=8, color="grey")

    plt.tight_layout()
    for ext in ("pdf", "png"):
        out = OUT_DIR / f"fig1_matrix_timeseries.{ext}"
        plt.savefig(out, dpi=200, bbox_inches="tight")
        print(f"Wrote {out}")
    plt.close(fig)


if __name__ == "__main__":
    main()
